"""Security-Generatoren: robots.txt, security.txt, .htaccess."""

from . import register, get_output_dir


# ── robots.txt ────────────────────────────────────────────

@register(
    name="robots-txt",
    category="Sicherheit",
    description="Generiert eine robots.txt für Suchmaschinen-Crawling",
    parameters=[
        {"name": "policy", "type": "select", "options": ["allow-all", "block-all", "custom"],
         "description": "Crawling-Richtlinie", "required": False},
        {"name": "sitemap_url", "type": "text", "description": "Sitemap-URL (optional)", "required": False},
        {"name": "blocked_paths", "type": "text",
         "description": "Blockierte Pfade (kommagetrennt, z.B. /admin,/api,/private)", "required": False},
    ],
)
def generate_robots_txt(params: dict) -> dict:
    policy = params.get("policy", "allow-all")
    sitemap = params.get("sitemap_url", "")
    blocked = params.get("blocked_paths", "")

    lines = ["# robots.txt — generated by AssetForge", ""]

    if policy == "block-all":
        lines += ["User-agent: *", "Disallow: /"]
    elif policy == "custom" and blocked:
        paths = [p.strip() for p in blocked.split(",") if p.strip()]
        lines += ["User-agent: *"]
        for p in paths:
            if not p.startswith("/"):
                p = "/" + p
            lines.append(f"Disallow: {p}")
        lines.append("Allow: /")
    else:
        lines += ["User-agent: *", "Allow: /"]

    if sitemap:
        lines += ["", f"Sitemap: {sitemap}"]

    out = get_output_dir() / "robots.txt"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {"files": [str(out)], "message": f"robots.txt generiert ({policy})"}


# ── security.txt ──────────────────────────────────────────

@register(
    name="security-txt",
    category="Sicherheit",
    description="Generiert eine security.txt (RFC 9116) für Vulnerability Disclosure",
    parameters=[
        {"name": "contact", "type": "text", "description": "Kontakt-E-Mail oder URL", "required": True},
        {"name": "expires", "type": "text", "description": "Ablaufdatum (YYYY-MM-DD)", "required": False, "default": "2026-12-31"},
        {"name": "preferred_languages", "type": "text", "description": "Bevorzugte Sprachen (z.B. de, en)", "required": False, "default": "de, en"},
        {"name": "policy_url", "type": "text", "description": "URL zur Security-Policy", "required": False},
        {"name": "encryption_url", "type": "text", "description": "URL zum PGP-Key", "required": False},
    ],
)
def generate_security_txt(params: dict) -> dict:
    contact = params.get("contact", "")
    expires = params.get("expires", "2026-12-31")
    langs = params.get("preferred_languages", "de, en")
    policy = params.get("policy_url", "")
    encryption = params.get("encryption_url", "")

    # Format contact as mailto: if it looks like an email
    if contact and "@" in contact and not contact.startswith("mailto:") and not contact.startswith("http"):
        contact = f"mailto:{contact}"

    lines = [
        "# security.txt — generated by AssetForge",
        "# See https://securitytxt.org/ (RFC 9116)",
        "",
        f"Contact: {contact}",
        f"Expires: {expires}T23:59:59.000Z",
    ]

    if langs:
        lines.append(f"Preferred-Languages: {langs}")

    if policy:
        lines.append(f"Policy: {policy}")

    if encryption:
        lines.append(f"Encryption: {encryption}")

    # Write to .well-known/security.txt
    well_known = get_output_dir() / ".well-known"
    well_known.mkdir(exist_ok=True)
    out = well_known / "security.txt"
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    # Also write to root
    root_out = get_output_dir() / "security.txt"
    root_out.write_text("\n".join(lines) + "\n", encoding="utf-8")

    return {"files": [str(out), str(root_out)], "message": "security.txt generiert (RFC 9116)"}


# ── .htaccess ─────────────────────────────────────────────

@register(
    name="htaccess",
    category="Sicherheit",
    description="Generiert eine .htaccess mit Security-Headers und Optimierungen",
    parameters=[
        {"name": "security_headers", "type": "boolean", "description": "Security-Headers hinzufügen (CSP, HSTS, etc.)", "required": False},
        {"name": "force_https", "type": "boolean", "description": "HTTPS erzwingen", "required": False},
        {"name": "gzip", "type": "boolean", "description": "GZIP-Kompression aktivieren", "required": False},
        {"name": "cache_control", "type": "boolean", "description": "Browser-Caching konfigurieren", "required": False},
        {"name": "block_dotfiles", "type": "boolean", "description": "Zugriff auf .Dateien blockieren", "required": False},
    ],
)
def generate_htaccess(params: dict) -> dict:
    sections = ["# .htaccess — generated by AssetForge"]

    if params.get("force_https"):
        sections.append("""
# ── HTTPS erzwingen ──
RewriteEngine On
RewriteCond %{HTTPS} off
RewriteRule ^(.*)$ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]""")

    if params.get("security_headers"):
        sections.append("""
# ── Security Headers ──
<IfModule mod_headers.c>
    Header set X-Content-Type-Options "nosniff"
    Header set X-Frame-Options "SAMEORIGIN"
    Header set X-XSS-Protection "1; mode=block"
    Header set Referrer-Policy "strict-origin-when-cross-origin"
    Header set Permissions-Policy "camera=(), microphone=(), geolocation=()"
    Header always set Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
    Header set Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'"
</IfModule>""")

    if params.get("gzip"):
        sections.append("""
# ── GZIP-Kompression ──
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css
    AddOutputFilterByType DEFLATE text/javascript application/javascript application/json
    AddOutputFilterByType DEFLATE application/xml application/xhtml+xml
    AddOutputFilterByType DEFLATE image/svg+xml
</IfModule>""")

    if params.get("cache_control"):
        sections.append("""
# ── Browser-Caching ──
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType image/jpg "access plus 1 year"
    ExpiresByType image/jpeg "access plus 1 year"
    ExpiresByType image/png "access plus 1 year"
    ExpiresByType image/gif "access plus 1 year"
    ExpiresByType image/svg+xml "access plus 1 year"
    ExpiresByType image/webp "access plus 1 year"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType text/javascript "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
    ExpiresByType application/pdf "access plus 1 month"
    ExpiresByType image/x-icon "access plus 1 year"
</IfModule>""")

    if params.get("block_dotfiles"):
        sections.append("""
# ── Dotfiles blockieren ──
<FilesMatch "^\\.">
    Order allow,deny
    Deny from all
</FilesMatch>

# .well-known erlauben
<Directory ".well-known">
    Order allow,deny
    Allow from all
</Directory>""")

    content = "\n".join(sections) + "\n"
    out = get_output_dir() / ".htaccess"
    out.write_text(content, encoding="utf-8")

    features = []
    if params.get("force_https"): features.append("HTTPS")
    if params.get("security_headers"): features.append("Security-Headers")
    if params.get("gzip"): features.append("GZIP")
    if params.get("cache_control"): features.append("Caching")
    if params.get("block_dotfiles"): features.append("Dotfiles-Schutz")

    msg = f".htaccess generiert ({', '.join(features) or 'Basis'})"
    return {"files": [str(out)], "message": msg}
